### ISSUE TITLE
Does Camerafeed support video file? 

### ISSUE THREAD

**Issue by albertyou2** [liquidg3/Camerafeed#1]
hi @liquidg3 
it is a very interesting work.But i do not have a camera, i want test your code with some video files,like .mp4 .avi files.
I just want to know how to modify your code to feed video file date into this program?
Thank you very much

**Comment by liquidg3** [comment]
Check settings.ini

**Comment by liquidg3** [comment]
Any luck? You see the setting to load videos? You'll want to set the setting for the "pi" to false I think.

**Comment by albertyou2** [comment]
hi @liquidg3 
As you mentioned I was trying to install opencv3.1.0 with both python2.7 and python3.4 on my respberry PI these days.It was a slow and painful process :-) .But finally I finished this work last night( i guess , without test )

Today I will try your project with python3.4.3 and opencv 3.1.0.I will let you know the result when i have a try!
Thank you ,have nice day!

**Comment by albertyou2** [comment]
I notice that in your instructions ,there is a description as below: 
4. Install additional dependencies bash $ pip setup.py develop 
I run this command but an error occured:
ERROR: unknown command "setup.py"
Do you mean  "python setup.py develop" here?

**Comment by albertyou2** [comment]
hi @liquidg3 
I have run your code successful ! good start~~!
But i found that it is much slower running on my raspyberry compare to the video on youtue.
Do you have any suggestion about how to speed it as fast as yours?Or could you please give me some info about hardware of  your raspberry PI(like cpu,memory,system,etc)?
Thank you!
