### ISSUE TITLE
get very low fps when i run with example video

### ISSUE THREAD

**Issue by albertyou2** [liquidg3/Camerafeed#2]
hi @liquidg3
I have run your code successful ! good start~!
But i found that it is much slower when running on my raspyberry compare to the video shows on youtue.
Do you have any suggestion about how to speed it up as fast as yours?Or could you please give me some info about hardware of your raspberry PI(like cpu,memory,system,etc)?
Thank you!,

EDIT:
I have tried run this program on raspberry pi 3 , it was still very slow ,,i got only 2 fps. And I have tried to play the origin video by using 'omxplayer -o hdmi 1.mp4' , i got 25 fps. 

Would this caused by runing with video file (not a camera)?I plan to buy a device just like yours and have a try again
Or Would this caused by using opencv3.1.0(compare to 3.0.0)？
What 's your fps when you running with video file ?

thank you !

**Comment by liquidg3** [comment]
Hey @albertyou2! The video you saw was run on my Macbook Pro. On the Pi, you have to run it in headless mode (without video window) and it works great.

**Comment by albertyou2** [comment]
Hey @liquidg3 
Do you mean I should set the  "show_window" to  False in settings.ini ?

**Comment by albertyou2** [comment]
@liquidg3 
I had test on my machine in "headless mode",i aslo got only 2 fps. 
I will use this repo on my PC,thank you !
